runtime: go
api_version: go1

handlers:
    - url: /api/.*
      script: _go_app

    - url: /(.+)
      static_files: static/\1
      upload: static/(.+)

    - url: /
      static_files: static/index.html
      upload: static/index.html





